### ISSUE TITLE
Add timeout option to Browser

### ISSUE THREAD

**Issue by clue** [clue/reactphp-buzz#1]

**Comment by clue** [comment]
This will very likely get an API somewhat similar to #15.

```php
$browser = $browser->withOptions(array('timeout' => 10));
$browser->get(…)
```

Any thoughts?

**Comment by clue** [comment]
I guess it makes sense to build this on top of cancellation support (#43) and then relying on react/promise-timer for the timeout cancellation.

**Comment by shtse8** [comment]
any updates? I want to have the timeout option.

**Comment by clue** [comment]
There are currently no immediate plans to build this from my end (no demand at the moment and more important issues such as #66), but I would be really happy to accept PRs :+1: 

*(If you need this for a commercial project and you want a quote, please check out my profile and send me an email)*

**Comment by r7l** [comment]
I would support a feature like that. I am trying to use make requests with sockets and it seems like that the response is never coming if the socket server went down. Maybe i am doing it wrong but when using the example code, the response will not be called.

**Comment by clue** [comment]
For the reference, as of #75 the README explicitly suggests using promise cancellation like this:

```php
$promise = $browser->get($url);

$loop->addTimer(2.0, function () use ($promise) {
    $promise->cancel();
});
```

Similarly, one can also use the react/promise-timer primitives like this:

```php
$promise = Promise\timeout($browser->get($url), 2.0, $loop);
```

Additionally, this component obeys the default connector timeout and allows explicitly passing a custom connection timeout:

```php
$connector = new \React\Socket\Connector($loop, array(
    'timeout' => 10.0
));

$browser = new Browser($loop, $connector);
```

@r7l A similar configuration applies to the clue/socks-react package and its documentation explicitly mentions SOCKS connection timeouts: https://github.com/clue/php-socks-react#connection-timeout

This means that we have plenty of options to implement "timeout options". I wonder what would be a sane way to integrate this into this library. In particular, timeout values have somewhat different implications if one downloads a huge response body or only processes its response headers. Any thoughts anybody? Also, PRs would be much appreciated 👍

**Comment by Rakdar** [comment]
To me it looks like there are three levels of different timeouts:
1. Low-Level connection-timeout as provided by `\React\Socket\Connector`.
2. High-Level header-timeout, in case you want to use process the body in a streaming manner.
3. High-Level response-incomplete-timeout, where the body should have been recived/buffered completly.

All three make sense and have their own use-cases. Case 1 is already covered in the Connector.

But 2 and 3 make the most sense in a this-or-that implementation. The header-timeout if ```$browser->withOptions(array('streaming' => true)```, otherwise the response-incomplete-timeout should be triggered.

Of course we could simply set only one timeout, and depending if the response should be streamed or not, trigger the corresponding error as explained before.

**Comment by clue** [comment]
Sounds good to me! I agree that the timeout should probably apply to the promise only as this is the main thing a user "waits" for. This means that if streaming is enabled, it does not take into account the full response body, but only the response headers. I think this makes sense for now and we can live with this if we add some documentation for this. We can still implement a "read timeout" (or similar) in the future for streaming responses :+1:

**Comment by ondrejmirtes** [comment]
Yes, I used that, thank you 😊

**Comment by roke22** [comment]
Hello, 
If i use the timeout with this code:

```
$loop->addTimer(10, function () use ($promise) {
    $promise->cancel();
});
```

The problem is now always have to wait 10 seconds, i want to finish the loop when all the http request are finish or when the timeout is reached. How to do it?  How can i cancel the addtimer function i scheluded if the request its done before?

Sorry for my english :(
Best Regards.

**Comment by ondrejmirtes** [comment]
```php
$timer = $loop->addTimer(10, function () use ($promise) {
    $promise->cancel();
});
$timer->cancel();
```

**Comment by roke22** [comment]
Seems that is not working. The idea is to cancel the timer if the response fuction is done with this code and finish the loop as soon as the all request respond.

```
foreach ($arrayData as $data){
    $promise = $client->post($data['url'], $data['header'], $data['post'])->then(
        function (ResponseInterface $response) use (&$result, $i, &$timer) {
            $result[] = (string)$response->getBody();
            $timer[$i]->cancel();
        },
        function (Exception $error) use (&$errors, $i, &$timer) {
            $errors[] =  $error->getMessage();
            $timer[$i]->cancel();
        }
    );
    $timer[$i] = $loop->addTimer(15, function () use ($promise) {
        $promise->cancel();
    });
    $i++;
}
```

But still waiting the 15 seconds even is the request load in 2 seconds. Seems that cancel flags the function to not be done but need to execute to check if have to execute or not and the loop still waiting the 15 seconds.

There is no way to "put out" that addTimer function i put on the queue to get out so the loop finish as soon as possible?

I hope you understand me, sorry for my english. :)

**Comment by roke22** [comment]
Appreciate your help. I used the response that Clue give me and works like a charm if the website have no problems. But if i did with a website that have some problems of connectivity or something similar the timeout is infinite.

I do not know if that is a bug or a error about how i am doing it. I give you a full working example:

```
<?php
use Clue\React\Buzz\Browser;
use Psr\Http\Message\ResponseInterface;
require 'vendor/autoload.php';

try {

    $loop = React\EventLoop\Factory::create();
    $client = new Browser($loop);
   
    $starttimeTotal = microtime(true);
    $result = array();
    $errors = array();

    $promise = \React\Promise\Timer\timeout($client->get("http://live.xtravelsystem.com")->then(
        function (ResponseInterface $response) use (&$result, $starttimeTotal) {
            $tmpResult = utf8_encode((string)$response->getBody());
            $endtime = microtime(true);
            $time = number_format(($endtime - $starttimeTotal), 2, ',', '.');
            $result[] = array ("http://live.xtravelsystem.com" => $tmpResult, "timeRequest" => $time );
        },
        function (Exception $error) use (&$errores, $dato, $starttimeTotal) {
            $endtime = microtime(true);
            $time = number_format(($endtime - $starttimeTotal), 2, ',', '.');
            $errors[] = array ("http://live.xtravelsystem.com" => $error->getMessage(), "timeRequest" => $time );
        }
    ),10.0,$loop);

    $loop->run();

    $endtimeTotal = microtime(true);
    $totalTime = number_format(($endtimeTotal - $starttimeTotal), 2, ',', '.');
   
    echo json_encode(array("error" =>$errors, "data" => $result, "timeSeconds" => $totalTime));
} catch (Exception $e) {
    echo 'Exception: ',  $e->getMessage(), "\n";
}
?>
```

Thank you very much.
