### ISSUE TITLE
Support Basic Access Authentication

### ISSUE THREAD

**Issue by clue** [clue/reactphp-buzz#10]
http://en.wikipedia.org/wiki/Basic_access_authentication

**Comment by clue** [comment]
Depends on https://github.com/reactphp/http-client/pull/32

**Comment by roke22** [comment]
Is not just adding a header like "Authorization" => "Basic base64_encode(User:Password)"
I try to add the header but is does not work.
Any information about it?

**Comment by clue** [comment]
@roke22 Yes, happy to hear you've sorted this out already! This feature has already been supported for quite some time, but I've just added some documentation for this with #109 :+1:
