### ISSUE TITLE
Connection refused from destination server..

### ISSUE THREAD

**Issue by royhg** [clue/reactphp-buzz#101]
Hi @clue, 
I have been using this scripts for months for my asynchronous process http submit and request, but suddenly it has been a week that my destination server was refused to receive connection for it.
My question is what kind of specific trouble for connection refused? it was close off tcp port?
The Exception file show that error from react tcpconnector.php?
Regards,
Roy

**Comment by clue** [comment]
HI @royhg! It sounds like there may be a problem with your remote server side, not this project. This project creates a TCP/IP connection to the remote server to send an HTTP request over this connection and await an HTTP response.

If your remote server is offline or actively refusing connections (perhaps you may have ended up on some firewall list?), then you'll start seeing connection issues.

I hope this helps :+1:
