### ISSUE TITLE
Explicitly close connection after response body to support servers ignoring Connection: close request header

### ISSUE THREAD

**Issue by jmoo** [clue/reactphp-buzz#102]
Some HTTP/1.1 servers do not honor the ```Connection: Close``` header. bufferResponse will never resolve when making requests to these. 

Here is an example fix:
https://github.com/jmoo/reactphp-buzz/commit/a9c27ecf02b820dfa82fb0acb312bd3c776750aa

The only problem is that ```\React\Promise\Stream\buffer``` doesn't resolve when maxLength is reached and changing it to resolve would be a BC break. We'd have to roll our own or start a discussion over on https://github.com/reactphp/promise-stream about adding a $resolveOnMaxLengthReached flag or something.

Related to #89

**Comment by clue** [comment]
@jmoo This is an interesting issue!

> Some HTTP/1.1 servers do not honor the Connection: Close header.

The server is clearly at fault for violating HTTP specs here: https://tools.ietf.org/html/rfc7230#section-6.3

That being said, I agree that this is something we should support nonetheless. The implementation likely depends on https://github.com/reactphp/http-client/issues/92 being addressed first. Once that PR is in, this should be trivial here.

**Comment by bartvanhoutte** [comment]
Seems like I'm running into this as well. Any workarounds for the moment?

**Comment by bartvanhoutte** [comment]
@jmoo just implemented something similar.

**Comment by clue** [comment]
Finally fixed via #161, please let me know if this works for you :+1:
