### ISSUE TITLE
documentation should include some reference/comparison to guzzle

### ISSUE THREAD

**Issue by yehosef** [clue/reactphp-buzz#103]
This looks like a nice library but I'm currently using Guzzle and I'm trying to understand why I should use this.

It would be helpful if the documentation included some reference guzzle and explain what the differences are - why someone would choose one over the other.  

Eg.  Perhaps, Buzz is much faster but offers fewer customization options.  So if you need raw speed Buzz is better but if you need X, Y or Z, then Guzzle is a better choice.

If the two are basically the same but Buzz is easier to use - that's also a selling point.  But something that can help me understand why I should switch.

**Comment by legionth** [comment]
Well Guzzle uses self-developed implementation of [promises](https://github.com/guzzle/promises), while this library is built on top of [ReactPHP](https://github.com/reactphp/). Which means you can use asynchronous approaches like asynchronous streaming see example: https://github.com/clue/reactphp-buzz/blob/master/examples/22-stream-stdin.php.

I don't think it is @clue business to compare his project with an another. The first sentences explain very good what are the advantages of this library(if you know the buzzwords of course :smile: ).

**Comment by yehosef-idt** [comment]
So, besides the React promises, are there any advantages?  

A comparison doesn't mean you have to bash the other guy or say "I'm the greatest". But it would be helpful to know if they should try out this lib and it will make their life better, or it's just another lib because I like green instead of blue.

**Comment by clue** [comment]
@yehosef This is an interesting question and I understand where you're coming from.

Unfortunately, comparing this library (and ReactPHP) with Guzzle or curl is a bit like comparing apples to oranges.

If all you're looking for is an HTTP client, you can use Guzzle or curl just fine (I also use both in a number of projects and are perfectly happy with them). This applies equally if you want to send single or multiple (concurrent) HTTP requests.

If you're looking for an async HTTP client and you want to send multiple concurrent HTTP requests or possibly perform other async operations concurrently, you may want to use this library. In particular, you can send multiple HTTP requests concurrently while also processing other I/O requests at the same time (such as a database query etc.). If you're building a truly async application, you will find that you *need* an async HTTP client that integrates with the rest of your application.

If you're using either project and are happy with it: Happy to hear, keep using it :-)

If you give both projects a try and have some insights: Make sure to share it with the world, comment in this ticket, send a tweet, write a blog post.

I hope this helps :+1:
