### ISSUE TITLE
Setting header X-MBX-APIKEY is not working

### ISSUE THREAD

**Issue by mpjraaij** [clue/reactphp-buzz#105]
Hi there,

I'm trying to set the X-MBX-APIKEY header, however somehow it's not getting through. Is there anything wrong with this code? (I'm 100% certain the endpoint and key are correct, tested in Postman)

At worst I should get a 400 (Bad Request), but I'm getting 401 (Unauthorized). It's not sending the key correctly it seems. Here's my code:

```php
$this->client->get($endpoint, [
    'X-MBX-APIKEY: ' . $secret['key']
]);
```

**Comment by clue** [comment]
Hi @mpjraaij, it looks like all you need to change is to make sure to use an assoc array for your custom headers here :-)

```php
$this->client->get($endpoint, [
    'X-MBX-APIKEY' => $secret['key']
]);
```

I hope this helps :+1:
