### ISSUE TITLE
Implement PSR-18

### ISSUE THREAD

**Issue by Nyholm** [clue/reactphp-buzz#107]
I've tried to implement PSR-18 to this library. But as you (@clue) told me a year ago, it might be impossible to do sync requests with this library. In guzzle we do something like:

```php
public function sendRequest(RequestInterface $request): ResponseInterface
{
    return $this->sendAsyncRequest($request)->wait();
}
```

Nevertheless, I'm about to open the vote on the specification and would like to hear your comments before that. 

See the specification: https://github.com/php-fig/fig-standards/blob/master/proposed/http-client/http-client.md
Read the blog post: https://medium.com/php-fig/the-http-client-psr-9c2535132980

**Comment by clue** [comment]
@Nyholm Thank you for reaching out and this excellent question!

 think you did an excellent job with the specification and the reasoning behind this as detailed in your previous Medium post. To me, PSR-18 looks good as-is and it makes perfect sense that async requests are of scope for this iteration. Traditional blocking and non-blocking code just don't mix well.

That being said, making any promise-based async API in ReactPHP available as a blocking API is relatively easy and works very similar to the example snippet you've posted above. By combining https://github.com/clue/reactphp-buzz#send with https://github.com/clue/reactphp-buzz#blocking, you end up with this (pseudo-code): 

```php
class Psr18Adaptor
{
    private $browser;

    public function __construct(LoopInterface $loop, Browser $browser = null)
    {
        if ($browser === null) {
            $browser = new Browser($loop);
        }

        $this->loop = $loop;
        $this->browser = $browser;
    }

    public function sendRequest(RequestInterface $request): ResponseInterface
    {
        return Block\await($this->browser->send($request), $this->loop);
    }
}
```

It's my understanding that having blocking code as part of a non-blocking library should usually be avoided as it may confuse newcomers. I think it makes sense to just leave this here for anybody who's interested in using an async HTTP client through the (blocking) PSR-18 API.

I hope this helps :+1:

**Comment by Nyholm** [comment]
I agree with you. Thank you. 

Aslo FYI. The readiness vote is open: https://groups.google.com/forum/#!topic/php-fig/BsroPEZcr_M
