### ISSUE TITLE
Timeouts no longer throw TimeoutException

### ISSUE THREAD

**Issue by AllenJB** [clue/reactphp-buzz#123]
https://github.com/clue/reactphp-buzz/blob/06f2be48302b386d7b8226cce3ab7601bd5564c8/src/Io/Transaction.php#L90-L97

Related to https://github.com/clue/reactphp-buzz/commit/32de45790aec4277876a2515e554c62966631b02

Timeouts no longer throw a TimeoutException, instead throwing a generic RuntimeException. This makes it more difficult to programmatically handle timeouts.

Could this change be reverted or is there a specific reason for it? Could the code throw a more specific exception instead please?

**Comment by clue** [comment]
@AllenJB Thanks for reporting, I understand where you're coming from and can see some use case for this :+1: 

Out of interest, can you provide a gist / example to highlight how you plan to use this?

Also, afaict this project *never* threw a `TimeoutException` unless I'm mistaken? This means this is not about what "no longer happens", but more about a future addition?

Are you aware of any similar APIs that handle this with a specific timeout exception? I'd like to flesh out a proper API and see how this is commonly used before jumping on the implementation.

It's my understanding a timeout exception is one possible source of problems and I'm not currently sold on the idea that this particular problem is "special" in a way that it warrants some special exception logic.

**Comment by clue** [comment]
Ping @AllenJB, can you update the status here, does the problem persist or did you mange to resolve this in the meantime?

**Comment by clue** [comment]
I'm having to close this for now as it hasn't received any input in a while and it's unlikely this will get traction any time soon. Please come back with more details if you think this is still relevant and we can reopen this +1

Thank you for your effort nonetheless, keep it up! :+1:
