### ISSUE TITLE
getCode is wrong

### ISSUE THREAD

**Issue by mastercho** [clue/reactphp-buzz#127]
In documentation says to get the status code is getCode() but actually is getStatusCode(). Also if use foreach to get every URL from array and do $client->get() inside foreach loop. Would this slowdown asynchronous loop from ReactPHP? 

Edit:
Just tried and if i go with foreach through $urls and then call $client->get(); is not going asynchronous so how to pass links to asnyc loop?

**Comment by clue** [comment]
> In documentation says to get the status code is getCode() but actually is getStatusCode().

The `ResponseInterface` defined by PSR-7 provides a `getStatusCode()` method which should give you access to the HTTP response status code.

Additionally, this library throws a `ResponseException` by default (see options) if a 4xx or 5xx response status code is encountered. This exception provides a `getCode()` method as mandated by the underlying exception base class. This method should give you access to the HTTP response status code and is equivalent to calling `$exception->getResponse()->getStatusCode()`.

> Edit:
> Just tried and if i go with foreach through $urls and then call $client->get(); is not going asynchronous so how to pass links to asnyc loop?

This sounds about right. See also the provided examples in the `examples/` folder. Additionally, if you're sending a lot of concurrent requests, you may want to limit this concurrency to a reasonable limit (say no more than a dozen or so at once). See also https://github.com/clue/reactphp-mq.

I hope this helps :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by mastercho** [comment]
Thanks for the answer.

I actually tried also https://github.com/clue/reactphp-mq but this results in a longer loop than usual foreach.
On tests, if i set 2 queues takes 18 minutes to go through 300 links and normal foreach with curl 6 minutes. Any other suggestions?

**Comment by clue** [comment]
Ouch, this really shouldn't have happened! I've been using this in a fair number of projects and it's not uncommon to see a 10x improvement when using an appropriate concurrency setting.

Of course it all depends on the particular problem you're trying to solve and also on what the remote end is capable of serving. Can you gist your code so more people can take a look at this? :+1:
