### ISSUE TITLE
Add to Response last effective Request or URI object

### ISSUE THREAD

**Issue by olegbaturin** [clue/reactphp-buzz#129]
I can't get latest effective URL after some redirects from the Response object.

https://www.php.net/manual/en/function.curl-getinfo.php
CURLINFO_EFFECTIVE_URL

**Comment by clue** [comment]
@olegbaturin Thanks for reporting, I agree that this feature makes sense :+1: 

Any suggestions API-wise? The response API is defined by PSR-7. https://github.com/guzzle/guzzle/issues/1166 might be relevant here.

**Comment by olegbaturin** [comment]
Effective URI is a part of Response, so you can extend PSR-7 ResponseInterface by getEffectiveUri() method. Latest URI object available in the Request object in the Transaction::onResponse() method.

**Comment by clue** [comment]
Thanks for bringing this up! I have to close this one as per #177 now that future development will focus on https://github.com/reactphp/http instead. If you feel this makes sense to port over, please file a new ticket over in the new repo and I'm happy to help review this :+1:
