### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by bartvanhoutte** [clue/reactphp-buzz#140]
Any plans on adding middleware to the client? I'm looking to collect statistics on HTTP requests.

**Comment by bartvanhoutte** [comment]
Created a PR, #141. Only supports intercepting the request so far.

**Comment by clue** [comment]
@bartvanhoutte Thanks for reporting, the feature request makes perfect sense!

We have to to figure out a decent API, but it looks like #141 might be a good starting point to discuss this :+1:

**Comment by bartvanhoutte** [comment]
PR #141 at the moment only supports altering a request. Altering a response seems fairly straightforward, but it would be nice if we could make it work with streaming enabled as well.

Also, it would be nice to be able to do both things in one and the same middleware, this would provide a nice way of doing things for #49 - adding the Content-Encoding header to the request and deflate the response in one middleware. Does this make sense?

**Comment by TaelmanTim** [comment]
@clue Any updates for this issue?

**Comment by clue** [comment]
As much as I'd like to commit to specific date, I can only say that I will get back to this feature as soon as time permits.

I still think that this feature makes perfect sense :+1:  However, there are currently no immediate plans to build this from my end (no demand at the moment and more important outstanding issues currently), but I would be really happy to accept PRs :+1: 

*(If you need this for a commercial project and you want to help sponsor this feature, feel free to reach out and send me an email)*

**Comment by jcchavezs** [comment]
I want to introduce distributed tracing middleware for this client, it would be really cool if we could have a middleware API for this.

**Comment by clue** [comment]
Again thanks for bringing this up! I have to close this one as per #177 now that future development will focus on https://github.com/reactphp/http instead. If you feel this makes sense to port over, please file a new ticket over in the new repo and I'm happy to help review this :+1:
