### ISSUE TITLE
Dropping support for PHP < 7.x

### ISSUE THREAD

**Issue by bartvanhoutte** [clue/reactphp-buzz#142]
When creating #141, I ran into some problems trying to maintain support for PHP 5.3. For example, $this isn't bound to the scope of a closure until PHP 5.4. On top of that, it's become quite the nuisance to create a development environment for PHP 5.3 with all the bells and whistles required to develop the library, even with Docker.

I think it might be time to drop support for PHP < 7.x. Maybe create a 3.0 release targeting modern PHP versions?

**Comment by clue** [comment]
@bartvanhoutte I understand where you're coming from! I agree this might be frustrating at times, but I see you've managed to work around the incompatibility in your PR.

I have no plans to drop legacy PHP versions any time soon, but this is definitely something to keep in mind for future development. There are still a number of outstanding issues in this repository that I would like to get solved first, but in the long run this repo will also introduce a BC break and bump the minimum PHP version :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by bartvanhoutte** [comment]
Perfect, thanks!
