### ISSUE TITLE
Consider replacing array of options with dedicated methods

### ISSUE THREAD

**Issue by clue** [clue/reactphp-buzz#154]
For instance:

```php
// old
$browser->withOptions(array('timeout' => 10))->post(…);

// new
$browser->withTimeout(10)->post(…);
```

This can be added in a 2.x release by deprecating the `withOptions()` method and still using this method under the hood. In a 3.0 release this method could be removed altogether.

Any input is welcome :+1:

**Comment by WyriHaximus** [comment]
I'll pick this up a create a PR

**Comment by WyriHaximus** [comment]
PR is up at #155
