### ISSUE TITLE
There is a way to send mutipart form data?

### ISSUE THREAD

**Issue by bohzio** [clue/reactphp-buzz#157]
Like this http://docs.guzzlephp.org/en/stable/request-options.html#multipart

**Comment by clue** [comment]
@bohzio Thanks for this excellent question!

At the moment, you can manually create the appropriate request body and pass it to the `send()`/`post()` method. As an alternative, you can use the `submit()` method to automatically send a request using `application/x-www-form-urlencoded`.

This project does not currently provide a built-in way to send a request using `multipart/form-data`. Implementing this isn't too hard from an API perspective. The major blocker (pun intended) here is the fact that this format is usually required for uploading large files and the filesystem is inherently blocking. https://github.com/reactphp/filesystem is still unstable and I don't like the idea of introducing this as a dependency here in its current form.

I still think that this feature makes perfect sense :+1: However, there are currently no immediate plans to build this from my end (no demand at the moment and more important outstanding issues currently), but I would be really happy to accept PRs :+1: 

*(If you need this for a commercial project and if you want to sponsor this feature, feel free to reach out and send me an email)*
