### ISSUE TITLE
Allow receiving the raw response body

### ISSUE THREAD

**Issue by mpociot** [clue/reactphp-buzz#159]
As discussed with @WyriHaximus:

This one is similar to #158 - but for responses.
To receive the initial part of the response, I need to convert the PSR7 response in the promise into a string.
When testing this, I noticed that the PSR7 implementation from Guzzle was doing something wrong regarding the Set-Cookie header. 
So instead of having to manually parse the PSR7 response into a string, it would be great if there would be a way to receive the actual raw response string - similar to what I can already do in the `data` events when streaming.

I'm not sure what's the best way to implement it - maybe just a __toString on the PSR7 response?
```
(new Browser())
    ->send($request)
    ->then(function (ResponseInterface $response) {
        var_dump((string)$response);
    });
```

**Comment by clue** [comment]
@mpociot This is an interesting one :+1: 

You can already use any library that supports serializing a PSR-7 `ResponseInterface` object, so I don't think it makes much sense to implement something here. For instance, this is the one that comes with this project:

```php
(new Browser())
    ->send($request)
    ->then(function (ResponseInterface $response) {
        echo \RingCentral\Psr7\str($response);
    });
```

**Comment by mpociot** [comment]
Yeah, the main reason I opened this issue though was that the PSR7 serialization library that I used (Guzzle) had issues with the serialization. It was fixed in the meantime, but I would’ve loved to just access the response as a stream/string without the additional overhead of serializing it (again) which could (and did) lead to an invalid response

**Comment by clue** [comment]
@mpociot I understand where you're coming from and agree that there's *some* use for this. I'm not sold on the idea of exposing this here because I believe this to be only useful for a small fraction of the user base and I don't like to prospect of having to maintain niche features that are rarely deemed useful let alone being used, but I'm open to discuss this again if more people show interest in this :+1:
