### ISSUE TITLE
Add caching support

### ISSUE THREAD

**Issue by clue** [clue/reactphp-buzz#3]

**Comment by clue** [comment]
I still think that this feature makes perfect sense :+1: However, there are currently no immediate plans to build this from my end (no demand at the moment and more important outstanding issues currently), but I would be really happy to accept PRs :+1: 

If you want to sponsor this feature, feel free to reach out +1

**Comment by nadar** [comment]
An easy example of how to wrap the request around https://reactphp.org/cache would be great already 👍
