### ISSUE TITLE
Implement gzip content encoding

### ISSUE THREAD

**Issue by clue** [clue/reactphp-buzz#49]
Also refs https://github.com/reactphp/http-client/issues/37

**Comment by clue** [comment]
This should be *fairly* easy to implement for the Promise-based API alone, but the streaming API would need a streaming zlib decoder, see also https://github.com/clue/php-zlib-react/issues/9.

**Comment by clue** [comment]
Note that this affected both `Transfer-Encoding: gzip` and `Content-Encoding: gzip`. The former can be used for transparent on-the-fly compression, while the latter is the one that is actually in use for most HTTP servers, see also https://stackoverflow.com/questions/11641923/transfer-encoding-gzip-vs-content-encoding-gzip and https://stackapps.com/questions/916/why-content-encoding-gzip-rather-than-transfer-encoding-gzip.

**Comment by irazasyed** [comment]
Any progress with this? Just hit a roadblock while working on a project.

**Comment by clue** [comment]
You can manually specify the required HTTP request headers and decompress the response body if the HTTP response indicates compression.

In the future, this should (will) be done automatically. As much as I'd like to commit to specific date, I can only say that we will get to this feature as soon as time permits.

*(If you need this for a commercial project and/or you want to sponsor this feature, feel free to reach out and send me an email)*

**Comment by clue** [comment]
I have to close this one as per #177 now that future development will focus on https://github.com/reactphp/http instead.

I've migrated this ticket to reactphp/http#377.
