### ISSUE TITLE
Support HTTP proxy

### ISSUE THREAD

**Issue by clue** [clue/reactphp-buzz#7]

**Comment by clue** [comment]
I've implemented this a few months ago and have been using this in a private project ever since.

Given I have no immediate use case besides this, I'll just dump this here for now and will postpone this until anybody sees fit.

https://github.com/clue-labs/http-client/compare/compat...clue-labs:proxy?expand=1

**Comment by gamebak** [comment]
Thanks for this commit, it's great, but it's still lacking something.
I want to go thru a http proxy where authentication is required as user and pass, any way to add user and password ?

Thanks,
Alex

**Comment by clue** [comment]
> I want to go thru a http proxy where authentication is required as user and pass, any way to add user and password ?

You should be able to pass the `Proxy-Authorization` header yourself to each call, e.g. http://stackoverflow.com/questions/10023636/http-spec-proxy-authorization-and-authorization-headers

Eventually, we should parse the given proxy server URI and use the user name and password to pass the header automatically (also refs #4).

**Comment by gamebak** [comment]
Thanks for the info, great commit!
