### ISSUE TITLE
Limit incoming Response size

### ISSUE THREAD

**Issue by DangerLifter** [clue/reactphp-buzz#89]

**Comment by DangerLifter** [comment]
I use quick solution: https://github.com/DangerLifter/php-buzz-react/commit/fcab8c3bad54b8d2a0ad08bde85afd3a6402d7b6

**Comment by clue** [comment]
Thanks for filing this ticket, there's indeed no way to limit the incoming response size right now. As an alternative, the documentation suggests using the streaming API: https://github.com/clue/php-buzz-react#streaming

I wonder what a "sane" limit could look like and what should happen if this limit is exceeded. Any thoughts anybody? Also, PRs would be much appreciated 👍
